declare module '*.svg';
declare module '*.pdf';
declare module '*.png';
declare module '*.jpg';
declare module '*.jpeg';
declare module '*.gif';
declare module '*.webp';
declare module '*.glb';
declare module '*.gltf';
